import type { ReactNode } from 'react';
import MissionMotion from './MissionMotion';

/**
 * Our Mission — each section is a giant Poppins title anchored bottom-left with
 * its body text set top-right in Lato. Full-width color bands shift tone as you
 * scroll to ease the reader through the page.
 */

type Tone = 'cream' | 'sage' | 'clay' | 'forest' | 'ink';

function Row({
  index,
  title,
  tone,
  hero,
  children,
}: {
  index: string;
  title: ReactNode;
  tone: Tone;
  hero?: boolean;
  children: ReactNode;
}) {
  const Title = hero ? 'h1' : 'h2';
  return (
    <section className={`mission-row tone-${tone}${hero ? ' mission-row--hero' : ''}`}>
      <div className="mission-row-inner">
        <div className="mission-row-body">
          <span className="mission-row-index">{index}</span>
          {children}
        </div>
        <Title className="mission-row-title">{title}</Title>
      </div>
    </section>
  );
}

export default function OurMission() {
  return (
    <div className="mission">
      <MissionMotion />

      {/* ---------- HERO (giant-title format, dramatic dark open) ---------- */}
      <Row
        index="Our Mission"
        tone="ink"
        hero
        title={
          <>
            Agroforestry just makes sense.{' '}
            <span className="title-sub">Think about it.</span>
          </>
        }
      >
        <p>
          Land made up of trees that produce food, support livelihoods, and remain
          a functioning ecosystem. That&apos;s not a new idea — it&apos;s how many
          of the world&apos;s most productive landscapes worked long before
          industrial agriculture.
        </p>
        <p className="row-statement">
          If you&apos;re here, your attention matters. Let&apos;s talk about why.
        </p>
        <p>
          Understanding VivaTTerra begins with a pause — a moment to reflect on how
          our attention, choices, and economic systems shape the living world
          around us.
        </p>
      </Row>

      {/* ---------- ROWS ---------- */}
      <Row index="(01)" title="The Work" tone="forest">
        <h3>Be part of real conservation.</h3>
        <p>
          VivaTTerra is a social-purpose business built for a single mission: to
          scale local, value-added agroforestry products on land that is at risk
          of being cleared for extractive uses such as industrial agriculture,
          mining, or logging.
        </p>
        <p className="row-emphasis">We are not a charity. We are not a campaign.</p>
        <p>
          We are a supply chain designed to make important natural land
          economically competitive. By creating markets for products made
          possible by healthy ecosystems, we help ensure that more of the value
          generated by the land remains with the people who live there.
        </p>
        <p className="row-statement">
          When forests support prosperous local economies, they become more
          valuable standing than cleared.
        </p>
      </Row>

      <Row index="(02)" title="The Name" tone="cream">
        <h3>VivaTTerra… what does this mean?</h3>
        <p>
          The name comes from two Latin roots: <em>vivat</em>, meaning &ldquo;long
          live&rdquo; or &ldquo;may it live,&rdquo; and <em>terra</em>, meaning
          &ldquo;earth,&rdquo; &ldquo;land,&rdquo; or &ldquo;soil.&rdquo; Together,
          it means <em>let the land live</em>.
        </p>
        <p>
          It is not a slogan. It is the operating principle behind every sourcing
          decision, every supplier relationship, and every product we bring to
          market — because land only remains as alive as the people who live there.
        </p>
        <p className="row-statement">Land stays alive when its people can thrive.</p>
        <p>
          The double <strong>TT</strong> is symbolic of grafting, a horticultural
          technique in which two plant stems are joined so they grow as one. It
          stresses mutual flourishing — the ethos of VivaTTerra. Natural land is
          both an ecosystem and an economy, and a healthy economy requires a
          healthy ecosystem.
        </p>
        <p>
          Consumer choice matters more than we tend to believe. Every purchase is a
          signal that shapes how products are made, how land is used, and who
          captures value. At its core, VivaTTerra is about interdependence:
          producers who care for the land make these foods possible, and consumers
          who choose them help sustain that care.
        </p>
      </Row>

      <Row index="(03)" title="How We Work" tone="sage">
        <h3>Relationships first, expansion second.</h3>
        <p>
          We work directly with the producers and processors behind the products
          we source. As a small, operationally focused team, we are bootstrapping
          this work carefully and incrementally — prioritizing strong
          relationships, product integrity, and long-term viability over rapid
          expansion.
        </p>
        <p>
          What we are building is more than a product supply chain. We are building
          the trust, partnerships, and market connections required for locally
          processed agroforestry products to compete and thrive. The goal is not
          simply to sell food, but to create the conditions for healthy ecosystems
          and prosperous rural livelihoods to reinforce one another over the long
          term.
        </p>
        <p>
          This is the foundation of a broader vision: a marketplace for important
          food products built on transparency and traceability — a platform
          designed to provide technical support to producers and meaningful
          information to consumers.
        </p>
      </Row>

      <Row index="(04)" title="The Problem" tone="ink">
        <h3>Every purchase is a signal. Most supply chains ignore that.</h3>
        <p>
          Supply chains are not neutral. They shape how land is used, how food is
          produced, and who captures value along the way. When land is treated
          primarily as a resource for extraction, the result is commodity supply
          chains — markets structured around volume, price, and standardization,
          rewarding the highest output at the lowest possible cost.
        </p>
        <p>
          The result: producers end up with no agency, and consumers are
          disconnected from the systems behind their purchase. VivaTTerra is an
          attempt to build supply chains where every sale directly promotes living
          ecosystems and human wellbeing.
        </p>
      </Row>

      <Row index="(05)" title="The Logic" tone="cream">
        <h3>The logic behind agroforestry sourcing.</h3>
        <p>
          Agroforestry systems are land with native trees, cultivated food crops,
          and in many cases livestock. This form of land management produces
          commercially valuable outputs while maintaining full ecological function:
          carbon storage, watershed regulation, biodiversity, and soil health.
        </p>
        <p>
          Agroforestry has been around long before there was a name for it. The
          economic case for it has simply been weak, because the markets for its
          products have been underdeveloped.
        </p>
        <p className="row-statement">Building those markets is the work.</p>
      </Row>

      <Row index="(06)" title="Origins" tone="clay">
        <h3>Why VivaTTerra begins with açaí.</h3>
        <p>
          My name is Fabrizio, and I am motivated by turning the often-overlooked
          value embedded within natural and economic systems into impactful market
          solutions that are both viable and resilient.
        </p>
        <p>
          The origins of VivaTTerra trace back to 2022, during research I was
          conducting in Madre de Dios, in the Peruvian Amazon. There I learned
          about one of the region&apos;s principal economic activities: small-scale
          gold mining. While mining provides the central source of income for many
          families, mercury is used in the extraction process.
        </p>
        <p>
          The consequences extend far beyond the mining sites. Mercury leaches into
          the soil and the river, contaminating the local water and food system. It
          is a potent neurotoxin associated with damage to the central nervous
          system, kidneys, and cardiovascular system. Research in Madre de Dios
          found significantly elevated mercury concentrations among residents living
          near mining areas, with some exceeding internationally recognized health
          thresholds.<sup className="cite-ref">1,2,3</sup>
        </p>
        <p>
          At the same time, I had the privilege of witnessing how truly abundant the
          land is. Madre de Dios is rich in fruits, nuts, oils, medicinal plants,
          and fibers — meaning the region can thrive off a prosperous local economy
          without requiring the forest to be cleared.
        </p>
        <p className="row-statement">
          The land itself is so rich — why are the strongest economic incentives
          still tied to its destruction?
        </p>
        <p>
          The challenge is no lack of resources, knowledge, or entrepreneurship. The
          challenge is that the markets for these products remain fragmented and too
          small in scale for an entire region to depend on them. For many
          communities, environmentally destructive activities are not chosen because
          they are preferred — they are chosen because they are among the few
          economic opportunities available.
        </p>
        <p>
          VivaTTerra exists because I believe land stewardship and markets are not
          opposing forces. When designed carefully, markets can become a mechanism
          that rewards care rather than extraction.
        </p>
        <p className="row-statement">
          I created VivaTTerra because I do not stand for extractive trade.
        </p>
        <p>
          In late 2025, I was introduced to a community açaí initiative through
          Samay O2 &ndash; Amazon Recovery, an NGO led by Massimo Giannini that
          implemented the açaí pulping facility in Ixiamas and is now developing
          a freeze-drying facility there &mdash; in a region otherwise dominated
          by industrial sugarcane, aiming to create new economic opportunities
          rooted in native biodiversity rather than monoculture expansion.
        </p>
        <p>
          I saw an opportunity to help build a market for a value-added product:
          freeze-dried açaí, processed at origin. Why açaí specifically &mdash;
          and why it&apos;s the right place to start &mdash; has its own case;
          you&apos;ll find it in full under Why It Matters.
        </p>
        <p className="row-statement">
          Açaí is where we begin, and it is where we build.
        </p>
        <p>
          The broader objective is a platform and a marketplace of products that
          make natural landscapes more valuable — and therefore more economically
          resilient to external threats of extraction. The result: a positive
          feedback loop between people&apos;s wellbeing and the wellbeing of the land
          they call home.
        </p>

        <ol className="citations">
          <li>
            Ashe, K. (2012). Elevated mercury concentrations in humans of Madre de
            Dios, Peru. <em>PLoS ONE</em>, 7(3), e33305.{' '}
            <a
              href="https://doi.org/10.1371/journal.pone.0033305"
              target="_blank"
              rel="noreferrer"
            >
              doi.org/10.1371/journal.pone.0033305
            </a>
          </li>
          <li>
            World Health Organization. <em>Mercury and Health.</em>{' '}
            <a
              href="https://www.who.int/news-room/fact-sheets/detail/mercury-and-health"
              target="_blank"
              rel="noreferrer"
            >
              who.int
            </a>
          </li>
          <li>
            Centers for Disease Control and Prevention.{' '}
            <em>Mercury Exposure and Health Effects.</em>{' '}
            <a
              href="https://www.cdc.gov/niosh/topics/mercury/default.html"
              target="_blank"
              rel="noreferrer"
            >
              cdc.gov
            </a>
          </li>
        </ol>
      </Row>

      <Row index="(07)" title="The People" tone="sage">
        <h3 className="people-intro">
          We are two people who believe deeply in this work — building VivaTTerra
          carefully, with the right partners, and for the long term.
        </h3>
        <div className="people-grid">
          <article className="person-card">
            <div className="person-photo">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src="/Photo/founders/Fabrizio_profile_photo.webp" alt="Fabrizio Colombo Fiore" />
            </div>
            <h4 className="person-name">Fabrizio Colombo Fiore</h4>
            <p className="person-role">Co-Founder</p>
            <p className="person-creds">
              B.Sc. Agricultural &amp; Environmental Economics (McGill) · M.Sc.
              Energy &amp; Climate Change Economics and Sustainable Finance
              (Barcelona School of Economics)
            </p>
            <p className="person-note">
              Mindfulness is central to my life, shaping how I relate to the world —
              informing how I think, make decisions, and take action.
            </p>
          </article>

          <article className="person-card">
            <div className="person-photo">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src="/Photo/founders/Ammar-founder-photo.webp" alt="Ammar Sathar" />
            </div>
            <h4 className="person-name">Ammar Sathar</h4>
            <p className="person-role">Co-Founder</p>
            <p className="person-creds">
              B.Eng. Electrical Engineering (Concordia) · Embedded Software Developer
            </p>
          </article>
        </div>
      </Row>

      <Row index="(08)" title="The Founders" tone="cream">
        <h3>A note from the founders.</h3>
        <p>We are at the beginning of this.</p>
        <p>
          The first product is moving. The supply chain is real. The relationships
          are built with care. But we are still learning — how to move product
          across borders efficiently, how to price for sustainability on both ends,
          how to tell this story in a way that connects without overclaiming.
        </p>
        <p>
          We are sharing this because we think transparency matters more than the
          appearance of being finished. VivaTTerra is being built in the open, and
          the people who find us early are part of that foundation.
        </p>
      </Row>

    </div>
  );
}
